# Generated by Django 3.2 on 2022-06-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_ledger_models', '0002_auto_20220614_1143'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='location',
            table='LOCATION',
        ),
    ]
