# Generated by Django 3.2 on 2022-06-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_ledger_models', '0003_alter_location_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='CURRENCY',
        ),
        migrations.AddField(
            model_name='location',
            name='CURRENCY_CODE',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
