# Generated by Django 3.2 on 2022-06-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_ledger_models', '0005_alter_location_update_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stg_trn_data',
            name='CURRENCY',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='stg_trn_data',
            name='LOCATION',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stg_trn_data',
            name='LOCATION_TYPE',
            field=models.CharField(blank=True, choices=[('S', 'Store'), ('W', 'Warehouse')], max_length=1, null=True),
        ),
    ]
